[tool.poetry]
name = "site"
version = "1.0.0"
description = ""
authors = ["Kevin James <KevinJames@thekev.in>"]

[tool.poetry.dependencies]
python = "^3.7"
Frozen-Flask = "0.18"
flask = "2.1.1"
flask-flatpages = "0.7.3"
pygments = "2.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
