[tool.poetry]
name = "builder"
version = "1.0.0"
description = ""
authors = ["Kevin James <KevinJames@thekev.in>"]

[tool.poetry.scripts]
freeze = "builder.main:freezer.freeze"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
Frozen-Flask = "0.18"
flask = "2.2.2"
flask-flatpages = "0.8.1"
pygments = "2.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
