[tool.poetry]
name = "builder"
version = "1.0.0"
description = ""
authors = ["Kevin James <KevinJames@thekev.in>"]

[tool.poetry.scripts]
freeze = "builder.main:freezer.freeze"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
frozen-flask = "1.0.1"
flask = "2.3.3"
flask-flatpages = "0.8.2"
pygments = "2.16.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
