[project]
name = "website"
version = "1.0.0"
description = ""
requires-python = ">=3.11,<4.0"

authors = [
    { name = "Kevin James", email = "KevinJames@thekev.in" },
]

dependencies = [
    "geopy==2.5.0",
    "jinja2==3.1.6",
    "markdown==3.10.3",
    "pandas==3.0.5",
    "plotly==7.0.0",
    "pygments==2.21.0",
]

[project.urls]
repository = "https://github.com/TheKevJames/web"

[project.scripts]
cache = "website.map:cache"
draw = "website.map:draw"
render = "website.main:render"

[dependency-groups]
dev = [
    "flake8-broken-line==1.0.0",
    "flake8-complicated-walrus==2.1.0",
    "flake8-import-restrictions==2.1",
    "flake8-requirements==2.3.0",
    "flake8==7.3.0",
    "pylint==4.0.8",
]

[tool.hatch.build.targets.wheel]
packages = ["website"]

[tool.ty.rules]
dynamic-function-decorator-return = "error"
missing-type-argument = "error"
possibly-unresolved-reference = "warn"
unsound-return-statement = "error"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
