[tool.poetry]
name = "site"
version = "1.0.0"
description = ""
authors = ["Kevin James <KevinJames@thekev.in>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "2.0.1"
flask-flatpages = "0.7.3"
frozen-flask = "0.15"
pygments = "2.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
